- name : Configure gsutil and required packages and deploy and execute the payload
  become: true
  become_method: sudo
  hosts: all
  gather_facts: no
  force_handlers: True
  tasks:
  - block:
    - name: Install Python packages
      pip:
        name: "{{ item }}"
      with_items:
        - gsutil
    rescue:
    - name: Install python packages
      shell: "pip3 install {{ item }}"
      with_items:
        - gsutil

  - name: Configure gsutil credentials
    template:
      src: "./templates/.boto.j2"
      dest: "~/.boto"

  - name: check if splash is configured in the boot command
    lineinfile:
      backup: true
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX=".*console=ttyS0,38400n8d'
      state: absent
    check_mode: true
    register: grub_cmdline_check
    changed_when: false

  - name: Backup /etc/default/grub  
    ansible.builtin.copy:
      src: /etc/default/grub
      dest: /etc/default/grub.xmigrate
      remote_src: yes
    when: grub_cmdline_check.found == 0
    
  - name: Add required kernel command line arguments
    lineinfile:
      backrefs: true
      path: /etc/default/grub
      regexp: "^(GRUB_CMDLINE_LINUX=\".*)\"$"
      line: 'GRUB_CMDLINE_LINUX="console=ttyS0,38400n8d console=tty0 net.ifnames=0 rd.blacklist=nouveau nvme_core.io_timeout=4294967295 crashkernel=auto"'
    when: grub_cmdline_check.found == 0
  
  - name: remove-kernel param
    replace:
      path: "/etc/default/grub" 
      regexp: 'rhgb quiet'
      replace: ''

  - name: Make sure splashimage= is not in the /etc/default/grub
    lineinfile:
      path: /etc/default/grub
      state: absent
      regexp: 'splashimage'

  - block:
    - name: <==Update grub config==>
      shell: "grub-mkconfig -o /boot/grub/grub.cfg"
      register: grubout
      become_user: root
      tags:
        - grubupdate
    rescue:
    - name: <==Trying Update grub2 config==>
      shell: "grub2-mkconfig -o /boot/grub2/grub.cfg"
      register: grubout
      become_user: root
      tags:
        - grubupdate