- name : Configure gsutil and required packages
  become: true
  become_method: sudo
  become_user: root
  hosts: all
  gather_facts: no
  force_handlers: True
  tasks:
  - block:
    - name: Install Python and dependencies for gsutil
      apt:
        pkg:
        - python3-dev
        - python3-pip
        - python3-setuptools 
        - libffi-dev
        - gcc
        update_cache: yes
    - name: upgrade pip3
      shell: "wget https://bootstrap.pypa.io/pip/3.5/get-pip.py | python3.5"
    rescue:
    - name: Update apt.. older way
      shell: "apt update -y"
    - name: Install Python-devel.. older way
      shell: "apt install gcc python3-dev python3-setuptools libffi-dev -y"
    tags:
      - devel

  - block:
    - name: Install Python packages
      pip:
        name: ['gsutil']
        executable: /usr/local/bin/pip3
    rescue:
    - name: Install python packages
      shell: "/usr/bin/pip3 install {{ item }}"
      with_items:
        - gsutil
      
  - name: Configure gsutil credentials
    template:
      src: "./templates/.boto.j2"
      dest: "~/.boto"

  - name: check if splash is configured in the boot command
    lineinfile:
      backup: true
      path: /etc/default/grub
      regexp: '^GRUB_CMDLINE_LINUX=".*console=ttyS0,38400n8d'
      state: absent
    check_mode: true
    register: grub_cmdline_check
    changed_when: false

  - name: Backup /etc/default/grub  
    ansible.builtin.copy:
      src: /etc/default/grub
      dest: /etc/default/grub.xmigrate
      remote_src: yes
    when: grub_cmdline_check.found == 0
    
  - name: Add required kernel command line arguments
    lineinfile:
      backrefs: true
      path: /etc/default/grub
      regexp: "^(GRUB_CMDLINE_LINUX=\".*)\"$"
      line: '\1 console=ttyS0,38400n8d"'
    when: grub_cmdline_check.found == 0
  
  - name: remove-kernel param
    replace:
      path: "/etc/default/grub" 
      regexp: 'rhgb quiet'
      replace: ''

  - name: Make sure splashimage= is not in the /etc/default/grub
    lineinfile:
      path: /etc/default/grub
      state: absent
      regexp: 'splashimage'

  - block:
    - name: <==Update grub config==>
      shell: "update-grub"
      tags:
        - grubupdate
    rescue:
    - name: <==Trying Update grub2 config==>
      shell: "update-grub2"
      register: grubout
      tags:
        - grubupdate