- name : Deploy and execute the payload
  become: true
  become_method: sudo
  become_user: root
  hosts: all
  gather_facts: no
  tasks:
    - name: <==Deploy payload==>
      copy:
        src: "../payloads/footprint/footprint"
        dest: "/tmp/footprint"
        mode: a+x
      tags:
        - deploy
        
    - name: <==Executing payload==>
      shell: "/tmp/footprint {{ project }} '{{ mongodb }}' {{ inventory_hostname }}"
      register: st
      tags:
        - exec

    - name: Debug
      debug:
        var: st
      tags:
        - msg