version: '3.1'

services:
  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    restart: unless-stopped
    ports:
      - "9042:9042"
      - "9160:9160"
    volumes:
      - cassandra:/cassandra
    environment:
      - "CASSANDRA_CLUSTER_NAME=cassandra-cluster"
      - "CASSANDRA_DC=DC1"
      - "CASSANDRA_RACK=Rack1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      # By default, Cassandra autodetects the available host memory and takes as much as it can.
      # Configure the limits according to the needs and memory availability.
      - "MAX_HEAP_SIZE=512M"
      - "HEAP_NEWSIZE=50M"
  app:
    image: xmigrate/xmigrate:latest
    container_name: app
    ports:
      - 80:80
      - 8000:8000
    environment:
      CASS_PASSWORD: "cassandra"
      CASS_USER: "cassandra"
      CASS_DB: "cassandra"
      BASE_URL: http://<server-ip>:8000/api
    depends_on:
     - cassandra

volumes:
  cassandra:
    driver: local