version: '3.1'

services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=xmigrate
      - POSTGRES_PASSWORD=xmigrate
      - POSTGRES_DB=xmigrate
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 5432:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    ports:
      - 5050:5050
    depends_on: 
      - postgres

  app:
    image: xmigrate/xmigrate:v0.1.6
    container_name: app
    environment:
      DB_USER: xmigrate
      DB_PASS: xmigrate
      DB_NAME: xmigrate
      DB_URL: postgres:5432
      BASE_URL: http://<server-ip>/api
    ports:
      - 80:80
    depends_on:
     - postgres

volumes:
  postgres:
    driver: local
  pgadmin:
    driver: local
