version: '3.1'

services:
  mongo:
    image: bitnami/mongodb:4.2
    restart: always
    environment:
      MONGODB_ROOT_USER: root
      MONGODB_ROOT_PASSWORD: example
      MONGODB_DATABASE: migration
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
     - mongo

  app:
    image: xmigrate/xmigrate:latest
    ports:
      - 8080:80
    environment:
      MONGO_DB: mongodb://root:example@mongo:27017/migration?authSource=admin
      BASE_URL: http://localhost:8000
    depends_on:
     - mongo

volumes:
  mongo:
    name: mongo