- name : Preparing the VM to be migrated to Azure
  become: true
  become_method: sudo
  become_user: root
  hosts: all
  gather_facts: no
  force_handlers: True
  tasks:
    - name: Copy content to file
      copy: 
        content:  | 
            NETWORKING=yes
            HOSTNAME=localhost.localdomain
        dest: /etc/sysconfig/network
        force: yes

    - name: Copy content to file
      copy: 
        content: |
          DEVICE=eth0
          ONBOOT=yes
          BOOTPROTO=dhcp
          TYPE=Ethernet
          USERCTL=no
          PEERDNS=yes
          IPV6INIT=no
          NM_CONTROLLED=no
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0
        force: yes
  
    - name: Modify udev rules to avoid generating static rules for the Ethernet interface
      shell: "ln -sf /dev/null /etc/udev/rules.d/75-persistent-net-generator.rules"
      
    - name: Update repos
      copy: 
        content: |
          [openlogic]
          name=CentOS-$releasever - openlogic packages for $basearch
          baseurl=http://olcentgbl.trafficmanager.net/openlogic/$releasever/openlogic/$basearch/
          enabled=1
          gpgcheck=0

          [base]
          name=CentOS-$releasever - Base
          #mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra
          baseurl=http://olcentgbl.trafficmanager.net/centos/$releasever/os/$basearch/
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

          #released updates
          [updates]
          name=CentOS-$releasever - Updates
          #mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=updates&infra=$infra
          baseurl=http://olcentgbl.trafficmanager.net/centos/$releasever/updates/$basearch/
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

          #additional packages that may be useful
          [extras]
          name=CentOS-$releasever - Extras
          #mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=extras&infra=$infra
          baseurl=http://olcentgbl.trafficmanager.net/centos/$releasever/extras/$basearch/
          gpgcheck=1
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7

          #additional packages that extend functionality of existing packages
          [centosplus]
          name=CentOS-$releasever - Plus
          #mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=centosplus&infra=$infra
          baseurl=http://olcentgbl.trafficmanager.net/centos/$releasever/centosplus/$basearch/
          gpgcheck=1
          enabled=0
          gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
        dest: /etc/sysconfig/network-scripts/ifcfg-eth0
        force: yes
     
    - name: clear yum data
      command: "yum clean all"
    
    - name: upgrade all packages to latest
      yum: name=* state=latest
    
    - name: Update grub entry
      shell: "sed -i '/GRUB_CMDLINE_LINUX/c\\GRUB_CMDLINE_LINUX=\"rootdelay=300 console=ttyS0 earlyprintk=ttyS0 net.ifnames=0\"
      ' /etc/default/grub"
      args:
        warn: false
   
    - name:  grub rebuild
      shell: "grub2-mkconfig -o /boot/grub2/grub.cfg"
   
    - name: Ensure the Hyper-V drivers are included in the initramfs
      shell: "sed -i '/add_drivers+=/c\\add_drivers+=\" hv_vmbus hv_netvsc hv_storvsc \"
      ' /etc/dracut.conf"
      args:
        warn: false
   
    - name: rebuild dracut
      shell: "dracut -f -v"
      
    - name: Install azure linux agent
      yum:
        name: 
          - WALinuxAgent
          - python-pyasn1
          - cloud-init
          - cloud-utils-growpart
          - gdisk 
          - hyperv-daemons
        state: latest
         
    - name: Enable azure linux agent
      systemd: 
        name: waagent
        enabled: yes
    
    - name: Configure waagent for cloud-init
      shell: |
        sed -i 's/Provisioning.UseCloudInit=n/Provisioning.UseCloudInit=y/g' /etc/waagent.conf
        sed -i 's/Provisioning.Enabled=y/Provisioning.Enabled=n/g' /etc/waagent.conf
        sed -i 's/Provisioning.RegenerateSshHostKeyPair=y/Provisioning.RegenerateSshHostKeyPair=n/g' /etc/waagent.conf
        echo "Adding mounts and disk_setup to init stage"
        sed -i '/ - mounts/d' /etc/cloud/cloud.cfg
        sed -i '/ - disk_setup/d' /etc/cloud/cloud.cfg
        sed -i '/cloud_init_modules/a\\ - mounts' /etc/cloud/cloud.cfg
        sed -i '/cloud_init_modules/a\\ - disk_setup' /etc/cloud/cloud.cfg
        echo "Allow only Azure datasource, disable fetching network setting via IMDS"
        cat > /etc/cloud/cloud.cfg.d/91-azure_datasource.cfg <<EOF
        datasource_list: [ Azure ]
        datasource:
            Azure:
                apply_network_config: False
        EOF
        if [[ -f /mnt/resource/swapfile ]]; then
        echo Removing swapfile - RHEL uses a swapfile by default
        swapoff /mnt/resource/swapfile
        rm /mnt/resource/swapfile -f
        fi
        echo "Add console log file"
        cat >> /etc/cloud/cloud.cfg.d/05_logging.cfg <<EOF
        # This tells cloud-init to redirect its stdout and stderr to
        # 'tee -a /var/log/cloud-init-output.log' so the user can see output
        # there without needing to look on the console.
        output: {all: '| tee -a /var/log/cloud-init-output.log'}
        EOF
        sed -i 's/ResourceDisk.Format=y/ResourceDisk.Format=n/g' /etc/waagent.conf
        sed -i 's/ResourceDisk.EnableSwap=y/ResourceDisk.EnableSwap=n/g' /etc/waagent.conf
      args:
        warn: false
  
    # - name: Removing wagent logs and files
    #   file:
    #     path: "{{ item }}"
    #     state: absent
    #   with_items:
    #     - /var/log/waagent.log
    #     - /var/lib/cloud/
    #     - /var/lib/waagent/  

    - name: Deprovision waagent
      shell: |
        cloud-init clean --logs --seed
        waagent -force -deprovision
        rm -f ~/.bash_history
        export HISTSIZE=0
     
    - name: Install azcopy
      shell: |
        wget https://azcopyvnext.azureedge.net/release20201021/azcopy_linux_amd64_10.6.1.tar.gz && \
        tar -zxf ./azcopy_linux_amd64_10.6.1.tar.gz && \
        mv ./azcopy_linux_amd64_10.6.1/azcopy /usr/bin && \
        chmod 777 /usr/bin/azcopy
    
    - name: Create resolv.conf
      copy: 
        content:  | 
            nameserver 8.8.8.8
            nameserver 1.1.1.1
        dest: /etc/resolv.conf
        force: yes

