- name : Configure aws-cli and required packages
  become: true
  become_method: sudo
  become_user: root
  hosts: all
  gather_facts: no
  force_handlers: True
  tasks:
  - name: Update packages
    shell: yum update

  - name: Ensure unzip is installed
    yum:
      name: unzip
      state: latest

  - name: Setup awscli
    shell: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -o awscliv2.zip
      ./aws/install --update
    args:
      warn: false
    
  - name: Create .aws directory
    file:
      path: "~/.aws/"
      state: directory
      mode: 0755
    become: false

  - name: Configure awscli credentials
    copy:
      src: "~/.aws/credentials"
      dest: "~/.aws/credentials"
    become: false

  - name: Configure aws region
    copy:
      src: "~/.aws/config"
      dest: "~/.aws/config"   
    become: false
  
  - name: Remove current kernel boot files
    shell: rm -f /boot/*
    ignore_errors: yes
    args:
      warn: false

  - block:
    - name: Install AWS supported linux kernel # AWS image build is not stable on non-generic kernals.
      apt:
        name: kernel-4.18.0-147.8.1*
        state: present
    rescue:
    - name: Install the kernel via shell
      shell: "yum install kernel-4.18.0-147.8.1* -y"
    tags:
        - devel

  - name: Configure new kernel boot files
    shell: |
      kernel=$(rpm -q kernel | grep 4.18.0-147.8.1 | sed 's/kernel/\/boot\/vmlinuz/')
      grubby --set-default $kernel
      grub2-mkconfig -o /boot/grub2/grub.cfg