- name : Configure aws-cli and required packages
  become: true
  become_method: sudo
  become_user: root
  hosts: all
  gather_facts: no
  force_handlers: True
  tasks:
  - name: Ensure unzip is installed
    apt:
      name: unzip
      state: latest

  - name: Setup awscli
    shell: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -o awscliv2.zip
      ./aws/install --update
    args:
      warn: false

  - block:
    - name: Upgrade to AWS linux kernel
      apt:
        name: linux-image-generic-hwe-20.04
        state: latest
    rescue:
    - name: Upgrade to AWS linux kernel
      shell: "apt install linux-image-generic-hwe-20.04 -y"
    tags:
        - devel

  - name: Remove EFI entries
    shell: mv /boot/efi/boot/grub/grub.cfg /boot/efi/boot/grub/grub.cfg.bak
    ignore_errors: yes

## Do below tasks manually if required
  # - name: Remove azure cloud related kernel if found
  #   shell: sudo apt remove linux-*-azure -y
  #   become_user: root
  #   become: yes

  # - name: Remove gcp cloud related kernel if found
  #   shell: sudo apt remove linux-*-gcp -y
  #   become_user: root
  #   become: yes
    
  - name: Update grub entries
    shell: |
      update-grub

  - name: Create .aws directory
    file:
      path: "~/.aws/"
      state: directory
      mode: 0755
    become: false

  - name: Configure awscli credentials
    copy:
      src: "~/.aws/credentials"
      dest: "~/.aws/credentials"
    become: false

  - name: Configure aws region
    copy:
      src: "~/.aws/config"
      dest: "~/.aws/config"
    become: false