- name : Configure aws-cli and required packages
  become_method: sudo
  become_user: root
  hosts: all
  gather_facts: no
  force_handlers: True
  tasks:
  - name: update packages
    shell: yum update

  - name: Ensure unzip is installed
    yum:
      name: unzip
      state: latest
    become: true

  - name: Setup awscli
    shell: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -o awscliv2.zip
      ./aws/install --update
    become: true
    args:
      warn: false
    
  - name: Create .aws directory
    file:
      path: "~/.aws/"
      state: directory
      mode: 0755

  - name: Configure awscli credentials
    copy:
      src: "~/.aws/credentials"
      dest: "~/.aws/credentials"

  - name: Configure aws region
    copy:
      src: "~/.aws/config"
      dest: "~/.aws/config"