- name : Deploy and execute the payload
  become: true
  hosts: localhost
  gather_facts: yes

    
  tasks:
    - name: Run the script
      shell: |
        if [ "$(uname -s)" == "Linux" ] && [ "$(uname -r)" == "3.12.28-4" ]; then
          echo "This VM's operating system is compatible with AWS."
        else
          echo "This VM's operating system is not compatible with AWS. The required kernel version is 3.12.28-4."
        fi

        architecture=$(uname -m)
        if [ "$architecture" == "x86_64" ]; then
          echo "This VM's processor architecture is compatible with AWS."
        else
          echo "This VM's processor architecture is not compatible with AWS. The supported processor architectures are x86_64 and ARM64."
        fi

        if [ -n "$(ifconfig eth0 | grep 'inet addr')" ]; then
          echo "This VM's network configuration is compatible with AWS."
        else
          echo "This VM's network configuration is not compatible with AWS. The network adapter must be configured with a static IP address."
        fi

        storage=$(df -Th / | awk 'FNR == 2 {print $2}')
        if [ "$storage" == "xfs" ]; then
          echo "This VM's storage configuration is compatible with AWS."
        else
          echo "This VM's storage configuration is not compatible with AWS. The supported file systems are XFS and EXT4."
        fi

        if [ $(ls /etc/ssh/ssh_host_* 2>/dev/null | wc -l) -ge 1 ]; then
          echo "This VM's security configuration is compatible with AWS."
        else
          echo "This VM's security configuration is not compatible with AWS. The VM must have SSH host keys generated."
        fi
        
      register: compatibility_check
      ignore_errors: yes

    - name: Display compatibility check results
      debug:
        var: compatibility_check.stdout_lines
      
    - name: <==Deploy payload==>
      copy:
        src: "../payloads/footprint/footprint"
        dest: "/tmp/footprint"
        mode: a+x
      tags:
        - deploy
        
    - name: <==Executing payload==>
      shell: "/tmp/footprint {{ project }} '{{ mongodb }}' {{ inventory_hostname }}"
      register: st
      tags:
        - exec

    - name: Debug
      debug:
        var: st
      tags:
        - msg