- name : Starting migration
  become: true
  become_method: sudo
  hosts: all
  gather_facts: no
  force_handlers: True
  tasks:
  - name: <== Deploy payload ==>
    copy:
      src: "../payloads/start_dd_aws.py"
      dest: "/tmp/start.py"
      
  - name: <== Executing payload ==>
    shell: "python3 /tmp/start.py {{ bucket }} {{ access_key }} {{ secret_key }} '{{ mongodb }}' {{ project }}"
    register: st

  - name: Message
    debug:
      var: st
