version: '3.1'

services:
  cassandra:
    image: cassandra:4.0
    container_name: cassandra
    restart: unless-stopped
    ports:
      - "9042:9042"
      - "9160:9160"
    volumes:
      - cassandra_data:/cassandra
    environment:
      - "CASSANDRA_CLUSTER_NAME=cassandra-cluster"
      - "CASSANDRA_DC=DC1"
      - "CASSANDRA_RACK=Rack1"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=50M

volumes:
  cassandra_data:
    driver: local
  cassandra2_data:
    driver: local