name: build and push docker image

on:
  release:
    types:
      - published
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.sha }}
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Calculate tag
        id: tagVer
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            tagVer=$(git tag --list --sort=-refname | head -1 | sed 's/v//')
          else
            tagVer="${{ github.sha }}"
          fi
          echo "tagVer=xmigrate/xmigrate:v$tagVer" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: "${{ steps.tagVer.outputs.tagVer }}"